// <auto-generated />
namespace GStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class movethemes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movethemes));
        
        string IMigrationMetadata.Id
        {
            get { return "201412031630528_movethemes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
