// <auto-generated />
namespace GStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class clientidforpagetemplateandtheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientidforpagetemplateandtheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201412041035021_clientidforpagetemplateandtheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
